FROM rust:1.83-slim-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    pkg-config \
    libssl-dev \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/* && \
    cargo install cargo-watch --locked

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY backend backend

CMD ["cargo", "watch", "-x", "run -p backend"]
